/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ap.dronemassa;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.Color;

/**
 *
 * @author Jacopo
 */
public class DroneGUI extends javax.swing.JFrame {

    /**
     * Creates new form DroneGUI
     */
    
    public static int PNL_WIDTH;
    public static int PNL_HEIGHT;
    
    private static int LBL_WIDTH;
    private static int LBL_HEIGHT;
    
    public DroneGUI() {
        initComponents();
        PNL_WIDTH = pnlDrones.getWidth();
        PNL_HEIGHT = pnlDrones.getHeight();
        
        LBL_WIDTH = 150;
        LBL_HEIGHT = 50;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDrones = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlDrones.setBounds(new java.awt.Rectangle(0, 0, 500, 500));
        pnlDrones.setName("pnlDrones"); // NOI18N
        pnlDrones.setLayout(null);

        btnAdd.setLabel("New Drone");
        btnAdd.setName("btnAdd"); // NOI18N
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDrones, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdd)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addGap(0, 387, Short.MAX_VALUE))
                    .addComponent(pnlDrones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        // create a new Drone
        Drone newDrone = new Drone();
        
        // create a new JLabel
        DroneLabel droneLabel = new DroneLabel();
        
        // generate random position and assign it to Drone and Label
        Position p = new Position((int) (Math.random() * (PNL_WIDTH - LBL_WIDTH)), (int) (Math.random() * (PNL_HEIGHT - LBL_HEIGHT)));
        
        droneLabel.setBounds((int) p.getX(), (int) p.getY(), LBL_WIDTH, LBL_HEIGHT);
        droneLabel.setVisible(true);
        droneLabel.setOpaque(true);
        droneLabel.setBackground(Color.LIGHT_GRAY);
        droneLabel.addMouseListener(new MouseAdapter() 
        {
            @Override
            public void mouseClicked(MouseEvent e)
            {
                if(newDrone.getFlyProperty())
                    newDrone.land();
                else
                {
                    DroneLabel label = (DroneLabel) e.getSource();
                    Position labelPos = new Position(label.getX(), label.getY());
                    newDrone.takeOff(labelPos);
                }
                    
            }
        });
        newDrone.addPropertyChangeListener(droneLabel);
        newDrone.takeOff(p);
        pnlDrones.add(droneLabel);        
        pnlDrones.repaint();
        
    }//GEN-LAST:event_btnAddMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DroneGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DroneGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DroneGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DroneGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DroneGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    public static javax.swing.JPanel pnlDrones;
    // End of variables declaration//GEN-END:variables
}
